import { IMAGES } from './assets';
import { BaoProduct, Testimonial, Outlet } from './types';

export const MEET_THE_BAO_PRODUCTS: BaoProduct[] = [
  {
    id: 'charsiu-special',
    name: 'Charsiu Special',
    badge: { text: 'BEST SELLER', type: 'best' },
    price: 26000,
    priceFormatted: 'Rp 26.000',
    description: 'Bakpao lembut dengan potongan daging gurih-manis bumbu charsiu rahasia dan sebutir salted egg yolk utuh yang lumer creamy.',
    image: IMAGES.heroCharsiu,
    category: 'savory',
    tags: ['SAVORY', 'SIGNATURE'],
    features: ['100% Salted Egg Yolk', 'Daging Tebal Halal', 'Saus Charsiu Karamel'],
    fillingRatio: '60% Isian : 40% Kulit',
    eggYolk: true,
  },
  {
    id: 'goguma-cream-cheese',
    name: 'Goguma Cream Cheese',
    badge: { text: 'VIRAL SWEET', type: 'viral' },
    price: 20000,
    priceFormatted: 'Rp 20.000',
    description: 'Ubi madu manis panggang berpadu gurihnya cream cheese premium yang lumer berlimpah di dalam adonan ungu selembut bantal.',
    image: IMAGES.gogumaCreamCheese,
    category: 'sweet',
    tags: ['SWEET', 'CHEESY'],
    features: ['Ubi Madu Alami', 'New Zealand Cream Cheese', 'Tanpa Pemanis Buatan'],
    fillingRatio: '55% Isian : 45% Kulit',
  },
  {
    id: 'choco-cheese-melt',
    name: 'Choco Cheese Melt',
    badge: { text: 'KIDS PICK', type: 'kids' },
    price: 20000,
    priceFormatted: 'Rp 20.000',
    description: 'Isian Belgian chocolate lumer manis dipadu keju cheddar gurih parut yang menyatu lumer sempurna saat disantap hangat.',
    image: IMAGES.chocoCheeseMelt,
    category: 'cheese',
    tags: ['SWEET', 'CHOCOLATE'],
    features: ['Belgian Dark Cocoa', 'Keju Cheddar Meleleh', 'Paling Disukai Anak'],
    fillingRatio: '55% Isian : 45% Kulit',
  },
  {
    id: 'taro-paste-supreme',
    name: 'Taro Paste Supreme',
    badge: { text: 'TRADISI', type: 'tradisi' },
    price: 20000,
    priceFormatted: 'Rp 20.000',
    description: 'Pasta ubi talas ungu pilihan yang diolah lembut alami tanpa aroma tiruan atau pewarna buatan. Rasa manis pas menenangkan.',
    image: IMAGES.taroPasteBao,
    category: 'sweet',
    tags: ['SWEET', 'NATURAL'],
    features: ['Talas Ungu Segar', 'Rendah Gula Alami', 'Aroma Tradisional'],
    fillingRatio: '50% Isian : 50% Kulit',
  },
  {
    id: 'sayur-kalimantan-pedas',
    name: 'Sayur Kalimantan Pedas',
    badge: { text: 'PEDAS GURIH', type: 'pedas' },
    price: 20000,
    priceFormatted: 'Rp 20.000',
    description: 'Sayuran tumis khas Kalimantan dengan jamur hioko, ebi wangi, dan cabai rawit pilihan. Renyah, gurih, dan pedas pas bikin melek.',
    image: IMAGES.sayurKalimantan,
    category: 'spicy',
    tags: ['SAVORY', 'SPICY'],
    features: ['Jamur Hioko Premium', 'Ebi Kalimantan Wangi', 'Cabai Rawit Segar'],
    fillingRatio: '60% Isian : 40% Kulit',
  },
  {
    id: 'martabak-bao-nusantara',
    name: 'Martabak Bao Nusantara',
    badge: { text: 'NUSANTARA', type: 'nusantara' },
    price: 20000,
    priceFormatted: 'Rp 20.000',
    description: 'Kombinasi kacang sangrai renyah, cokelat lezat, wijen, dan keju aroma martabak klasik di dalam roti bao kukus empuk.',
    image: IMAGES.martabakBao,
    category: 'sweet',
    tags: ['SWEET', 'NUTTY'],
    features: ['Kacang Tanah Sangrai', 'Cokelat Klasik', 'Wijen & Parutan Keju'],
    fillingRatio: '55% Isian : 45% Kulit',
  },
];

export const MOOD_PRODUCTS: BaoProduct[] = [
  {
    id: 'special-komplit',
    name: 'Special Komplit',
    badge: { text: 'SIGNATURE', type: 'special' },
    price: 32000,
    priceFormatted: 'Rp 32.000',
    description: 'Tiga lapis kenikmatan: daging charsiu empuk gurih, cincangan ayam jamur, dan telur asin emas utuh dalam satu bao jumbo.',
    image: IMAGES.heroCharsiu,
    category: 'savory',
    tags: ['DAGING', 'SUPER FILLING'],
  },
  {
    id: 'goguma-mochi',
    name: 'Goguma Mochi Melt',
    badge: { text: 'CHEWY', type: 'viral' },
    price: 20000,
    priceFormatted: 'Rp 20.000',
    description: 'Sensasi kenyal mochi susu yang bisa ditarik dipadu lembutnya pasta ubi manis panggang Korea.',
    image: IMAGES.gogumaCreamCheese,
    category: 'sweet',
    tags: ['SWEET', 'MOCHI PULL'],
  },
  {
    id: 'goguma-mozzarella',
    name: 'Goguma Mozzarella',
    badge: { text: 'PULL CHEESE', type: 'best' },
    price: 22000,
    priceFormatted: 'Rp 22.000',
    description: 'Keju mozzarella mulur berpadu kontras manis gurih ubi madu dalam kulit bao ungu lembut.',
    image: IMAGES.gogumaCreamCheese,
    category: 'cheese',
    tags: ['CHEESE', 'TARIKAN PANJANG'],
  },
  {
    id: 'salted-egg-lava',
    name: 'Salted Egg Custard Lava',
    badge: { text: 'MOLTEN LAVA', type: 'best' },
    price: 22000,
    priceFormatted: 'Rp 22.000',
    description: 'Saus custard kuning telur asin manis-gurih yang meleleh keluar begitu bakpao hangat dibelah dua.',
    image: IMAGES.saltedEggLava,
    category: 'cheese',
    tags: ['SAVORY', 'LAVA LELEH'],
  },
  {
    id: 'wintermelon-mala',
    name: 'Wintermelon Mala Crunch',
    badge: { text: 'SPICY MALA', type: 'pedas' },
    price: 24000,
    priceFormatted: 'Rp 24.000',
    description: 'Paduan labu kundur segar penyejuk berpadu sensasi bumbu mala Sichuan pedas merica menggugah selera.',
    image: IMAGES.sayurKalimantan,
    category: 'spicy',
    tags: ['SPICY', 'MALA SICHUAN'],
  },
  {
    id: 'choco-cheese-classic',
    name: 'Choco Cheese Classic',
    badge: { text: 'FAVORITE', type: 'kids' },
    price: 20000,
    priceFormatted: 'Rp 20.000',
    description: 'Perpaduan klasik cokelat pasta kental dan keju cheddar gurih yang tak pernah salah di setiap waktu santap.',
    image: IMAGES.chocoCheeseMelt,
    category: 'sweet',
    tags: ['SWEET', 'CLASSIC MELT'],
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'testi-1',
    rating: 5,
    text: 'Jujur gak pernah nemu bakpao seenak ini di Tangerang. Charsiu Special-nya beneran melting, salted egg-nya bulat utuh gurih banget! Kulitnya selembut kapas.',
    name: 'Stephanie Amanda',
    role: 'Alam Sutera Foodie',
    initials: 'SA',
  },
  {
    id: 'testi-2',
    rating: 5,
    text: 'Goguma Cream Cheese-nya nagih parah! Manisnya pas, gak enek sama sekali. Kulit bakpaonya empuk fluffy kayak bantal dan gak nempel di gigi.',
    name: 'Kevin Wijaya',
    role: 'Verified Customer',
    initials: 'KW',
  },
  {
    id: 'testi-3',
    rating: 5,
    text: 'Langganan buat hampers kantor dan kirim ke keluarga. Packaging merahnya cakep mewah, isinya beneran padet tanpa pelit! Semua rekan kantor pada ketagihan.',
    name: 'Melinda R.',
    role: 'Corporate Order Lead',
    initials: 'MR',
  },
];

export const OUTLET_DATA: Outlet = {
  id: 'outlet-alam-sutera',
  name: 'Bakpaonya Koko – Alam Sutera',
  tagline: 'Flagship Boutique Outlet & Steamer Station',
  address: 'Jl. Jalur Sutera Tim. No.16A No.2, Kunciran, Kec. Pinang, Kota Tangerang, Banten 15144 (Verona Junction Blok B-07)',
  hours: 'Setiap Hari: 08.00 - 20.00 WIB',
  phone: '0813-9876-8046',
  whatsapp: 'https://wa.me/6281398768046?text=Halo%20Koko!%20Saya%20mau%20pesan%20bakpao%20hangat',
  mapsUrl: 'https://maps.google.com/?q=Bakpaonya+Koko+Alam+Sutera',
  status: 'Buka Sekarang',
};

export const INSTAGRAM_POSTS = [
  {
    id: 'ig-1',
    title: 'Bakpao Salted Egg Lava',
    subtitle: 'Golden yolk melt yang meluap di setiap belahan',
    image: IMAGES.saltedEggLava,
    tag: '#SaltedEggLava',
    likes: '1.4k',
  },
  {
    id: 'ig-2',
    title: 'Bukan Bakpao Biasa',
    subtitle: 'Rasio isian melimpah 60% dengan kulit super fluffy',
    image: IMAGES.heroCharsiu,
    tag: '#BakpaonyaKoko',
    likes: '2.8k',
  },
  {
    id: 'ig-3',
    title: 'Sayur Kalimantan Pedas',
    subtitle: 'Jamur hioko & ebi wangi tumis gurih mantap',
    image: IMAGES.sayurKalimantan,
    tag: '#SayurKalimantan',
    likes: '1.1k',
  },
  {
    id: 'ig-4',
    title: 'Sweet Goguma Cream Cheese',
    subtitle: 'Perpaduan ubi madu panggang & keju lembut',
    image: IMAGES.gogumaCreamCheese,
    tag: '#GogumaSeries',
    likes: '3.2k',
  },
];
